### ISSUE TITLE
Plugin updated to latest dart sdk >=3.5.0

### ISSUE THREAD

**Issue by chreck** [fluttercommunity/get_version#20]
If someone is interested and does not want to use [device_info_plus](https://pub.dev/packages/device_info_plus) pub package. I updated the package to latest dart sdk 3.5.0 .

See [get_version](https://github.com/milkinteractive/get_version)

Use in your `pubspec.yaml`

```
  get_version:
    git:
      url: https://github.com/milkinteractive/get_version.git
      ref: 1.0.1
```

Have fun.
